apiVersion: v1
kind: Service
metadata:
  name: app-standby-emily
  labels:
    app: app-standby-emily
spec:
  selector:
    app: app-standby-emily
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP